AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  litemall

  litemall backend

Globals:
  Function:
    Timeout: 60

Resources:
  # create api-gateway resource：https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html
  FunctionApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: aws lambda's api gateway
      Name: lambda-gateway
      CorsConfiguration:
        AllowOrigins:
          - "https://*"
          - "http://*"
        AllowHeaders:
          - "Content-Type"
          - "X-Litemall-Admin-Token"
        AllowMethods:
          - "*"
        AllowCredentials: true
  litemallFunction:
    Type: AWS::Serverless::Function
    Properties:
      VpcConfig:
        SecurityGroupIds:
          - '{{resolve:ssm:/litemall/prod/vpc/application-security-group}}'
        SubnetIds:
          - '{{resolve:ssm:/litemall/prod/vpc/private-subnet-one}}'
          - '{{resolve:ssm:/litemall/prod/vpc/private-subnet-two}}'
      MemorySize: 2048
      Handler: run.sh
      CodeUri: litemall-all/
      Runtime: java17
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions
      Environment:
        Variables:
          RUST_LOG: info
          READINESS_CHECK_PATH: /admin/index/index
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=4 -XX:+UseParallelGC
          PORT: 8081
          DB_CLUSTER_ENDPOINT: '{{resolve:ssm:/litemall/prod/db/cluster-endpoint}}'
          DB_MASTER_USERNAME: '{{resolve:ssm:/litemall/prod/db/master-username}}'
          DB_MASTER_PASSWORD: '{{resolve:ssm:/litemall/prod/db/master-password}}'
          REDIS_CACHE_ENDPOINT: '{{resolve:ssm:/litemall/prod/redis/endpoint}}'
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: /litemall/prod/*
      Layers:
        - !Sub arn:aws:lambda:us-west-2:753240598075:layer:LambdaAdapterLayerX86:21
      Events:
        litemallApi:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: FunctionApiGateway
            Path: /{proxy+}
            Method: ANY
Outputs:
  MobielMallSite:
    Description: "Moble Mall Site URL"
    Value: !Sub "https://${FunctionApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/index.html"
  AdminWebHomepage:
    Description: "Admin endpoint Homepage URL"
    Value: !Sub "https://${FunctionApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/mgmt/index.html"
  AdminApiURL:
    Description: "Admin endpoint API URL"
    Value: !Sub "https://${FunctionApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/admin/index/index"

